<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120307123726 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE polls (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, body LONGTEXT NOT NULL, is_active TINYINT(1) NOT NULL, date DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE polls_options_hits (id INT AUTO_INCREMENT NOT NULL, poll_option_id INT DEFAULT NULL, session VARCHAR(64) NOT NULL, ip VARCHAR(16) NOT NULL, date DATETIME NOT NULL, INDEX IDX_4FB25B366C13349B (poll_option_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE polls_options (id INT AUTO_INCREMENT NOT NULL, poll_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, INDEX IDX_762212FD3C947C0F (poll_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE polls_options_hits ADD CONSTRAINT FK_4FB25B366C13349B FOREIGN KEY (poll_option_id) REFERENCES polls_options(id)");
        $this->addSql("ALTER TABLE polls_options ADD CONSTRAINT FK_762212FD3C947C0F FOREIGN KEY (poll_id) REFERENCES polls(id)");
        
        
        // custom
        $this->addSql("ALTER TABLE `polls_options_hits` ADD INDEX FK_762212FD3C947C0F2 ( `poll_option_id` , `session` ) ;" );
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE polls_options DROP FOREIGN KEY FK_762212FD3C947C0F");
        $this->addSql("ALTER TABLE polls_options_hits DROP FOREIGN KEY FK_762212FD3C947C0F2");
        $this->addSql("ALTER TABLE polls_options_hits DROP FOREIGN KEY FK_4FB25B366C13349B");
        $this->addSql("DROP TABLE polls");
        $this->addSql("DROP TABLE polls_options_hits");
        $this->addSql("DROP TABLE polls_options");
    }
}
