<?php

namespace SFBCN\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * Gets past events
     * @return array
     */
    public function getPastEvents()
    {
        return $this->_em->createQuery('SELECT e from SFBCNWebsiteBundle:Event e WHERE e.datetime < :datetime ORDER BY e.datetime DESC')
                    ->setMaxResults(15)
                    ->setParameter('datetime', new \DateTime())
                    ->getResult();
    }

    /**
     * Gets immediate next event
     * @return mixed
     */
    public function getNextEvent()
    {
        try {
            return $this->_em->createQuery('SELECT e from SFBCNWebsiteBundle:Event e WHERE e.datetime > :datetime ORDER BY e.datetime ASC')
                        ->setMaxResults(1)
                        ->setParameter('datetime', new \DateTime())
                        ->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    /**
     * Gets future event excluding immediate next one
     * @return array
     */
    public function getFutureEvents()
    {
        return $this->_em->createQuery('SELECT e from SFBCNWebsiteBundle:Event e WHERE e.datetime > :datetime ORDER BY e.datetime ASC')
                    ->setFirstResult(1)
                    ->setMaxResults(15)
                    ->setParameter('datetime', new \DateTime())
                    ->getResult();
    }
}