<?php

namespace SFBCN\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * Gets past events
     * @param integer $max
     * @return array
     */
    public function getPastEvents($max = 15)
    {
        return $this->_em->createQuery('SELECT e from SFBCNWebsiteBundle:Event e WHERE e.datetime < :datetime ORDER BY e.datetime DESC')
                    ->setMaxResults($max)
                    ->setParameter('datetime', new \DateTime())
                    ->getResult();
    }

    /**
     * Gets immediate next event
     * @return mixed
     */
    public function getNextEvent()
    {
        return $this->_em->createQuery('SELECT e from SFBCNWebsiteBundle:Event e WHERE e.datetime > :datetime ORDER BY e.datetime ASC')
                    ->setMaxResults(1)
                    ->setParameter('datetime', new \DateTime())
                    ->getOneOrNullResult();
    }

    /**
     * Gets future event excluding immediate next one
     * @param integer $max
     * @return array
     */
    public function getFutureEvents($max = 15)
    {
        return $this->_em->createQuery('SELECT e from SFBCNWebsiteBundle:Event e WHERE e.datetime > :datetime ORDER BY e.datetime ASC')
                    ->setFirstResult(1)
                    ->setMaxResults($max)
                    ->setParameter('datetime', new \DateTime())
                    ->getResult();
    }
}