<?php

namespace SFBCN\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SFNewRepository extends EntityRepository
{
}